graph TD
  Pequod --> Chartroom
  Pequod --> Maps
  Pequod --> Logbook
  Ocean --> England_1
  Ocean --> England_2
  Armory --> Gam
  Armory --> England_1
  England_1 --> Spouter_inn
  England_1 --> Crows_nest
  England_1 --> Whaleboat
  England_1 --> Tackle
