flowchart TB
  classDef default fill:#3BA17B,stroke:#3BA17B,color:gold;
  Leviathan:::default
  Leviathan --> Pequod
  Leviathan --> Ocean
  Leviathan --> Armory
  Leviathan --> Awhalin
  subgraph Pequod [Pequod]
    Pequod --> Chartroom
    Pequod --> Maps
    Pequod --> Logbook
  end
  subgraph Ocean [Ocean]
    Ocean --> England_1
    Ocean --> England_2
  end
  subgraph Armory [Armory]
    Armory --> Gam
    Armory --> England_1
  subgraph England_1 [England_1]
    England_1 --> Blubber_room
    England_1 --> Crows_nest
    England_1 --> Whaleboat
    England_1 --> Tackle
    England_1 --> Line
    England_1 --> Harpoon
  end
  end
  subgraph Awhalin [Awhalin]
    Awhalin --> Gam
    Awhalin --> England_1
  subgraph England_1 [England_1]
    England_1 --> Mapple
    England_1 --> Peleg
    England_1 --> Bildad
    England_1 --> Flask
    England_1 --> Stubb
    England_1 --> Fedallah
    England_1 --> Tashtego
    England_1 --> Daggoo
    England_1 --> Elijah
    England_1 --> Ahab
    England_1 --> Starbuck
    England_1 --> Ishmael
    England_1 --> Queequeg
    England_1 --> Rachel
  end
  end